# Generated by Django 5.2.8 on 2025-11-14 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=300)),
                ('n_cnes', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('numero_patrimonio', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('funcionando', 'Funcionando'), ('quebrado', 'Quebrado'), ('em manutencao', 'Em Manutenção'), ('roubado', 'Roubado'), ('em estoque', 'Em estoque'), ('fora de estoque', 'Fora de Estoque')], max_length=25)),
                ('qtde_estoque', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciador.categoria')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='gerenciador.funcionario')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('destino_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='gerenciador.funcionario')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador.equipamento')),
                ('origem_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='gerenciador.funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='gerenciador.unidade'),
        ),
    ]
